#Testing about CI

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- powershell: |
    $filePath = "Common"
    if (-not (Test-Path $filePath)) {
        Write-Output "The file '$filePath' does not exist."
        exit 1  # Fail the task
    } else {
        Write-Output "The file '$filePath' exists."
    }
  displayName: 'Check File Existence'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*[Tt]ests*/*.csproj'
    # arguments: '--configuration release --output $(Build.ArtifactStagingDirectory) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
    # publishTestResults: true
    arguments: '--configuration $(BuildConfiguration) --collect:"Code coverage"'
    publishTestResults: true
    publishCodeCoverage: true
- task: PowerShell@2
  displayName: 'Check code coverage'
  inputs:
    targetType: 'inline'
    script: |
      $coverageReport = "$(Build.SourcesDirectory)\<path_to_coverage_report>\coverage.xml"
      
      # Read the coverage percentage from the XML report
      $coveragePercentage = Select-String -Path $coverageReport -Pattern "<Percent>" | Select-Object -First 1
      $coveragePercentage = $coveragePercentage -replace '.*<Percent>(\d+).*','$1'

      if ($coveragePercentage -lt 80) {
        Write-Host "Code coverage is less than 80%. Stopping the build."
        exit 1
      } else {
        Write-Host "Code coverage is greater than or equal to 80%. Continuing the build."
      }


# - task: PublishCodeCoverageResults@2
#   inputs:
#     # codeCoverageTool: 'Cobertura'
#     summaryFileLocation: '**/*coverage.cobertura.xml'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/StudentManagementAPI.csproj'
    arguments: '--configuration release --output $(Build.ArtifactStagingDirectory) '
    

# - task: CopyFiles@2
#   inputs:
#     Contents: '**/*.dll'
#     TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dll_file'
    publishLocation: 'Container'
